apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /prenomservice(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: prenomservice
            port:
              number: 80
      - path: /rentalservice(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: rentalservice
            port:
              number: 8080
